Database/src/models.py
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy import LargeBinary
from datetime import date
from src import db

class Track(db.Model):
    __tablename__ = "track"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(unique=False)
    artist: Mapped[str] = mapped_column(unique=False) # To become an attribute linking to a user in the future user/account table 
    data: Mapped[bytes] = mapped_column(LargeBinary)
    cover: Mapped[bytes] = mapped_column(LargeBinary)
    release_date: Mapped[date] = mapped_column(nullable=True)

Database/src/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from Common.track import create_track_model
from base64 import b64encode

# Initialise database
db = SQLAlchemy()
Track = create_track_model(db)

def create_app():
    """Creates the database microservice's flask app with its configuration, initialises the database's tables,  
    and links the app to the routes in the views file.   

    Returns
    -------
    Flask
        the database microservice's Flask app 
    """

    app = Flask(__name__)   
    app.config["SQLALCHEMY_DATABASE_URI"]="sqlite:///database.db"

    db.init_app(app)

    # Checks if an instance of the database already exists.
    with app.app_context():
        db.drop_all()
        db.create_all()

    # Point to the routes in the views file. 
    from src.views import main
    app.register_blueprint(main)

    # Setting up a new filter for jinja to decode base64 images in HTML files. TO BE PUT IN AN extensions.py FILE IN THE FUTURE WITH OTHER EXTENSIONS AND CONFIG COMMANDS.
    @app.template_filter('to_base64')
    def to_base64_filter(binary_data):
        return b64encode(binary_data).decode('utf-8')

    app.jinja_env.filters['to_base64'] = to_base64_filter

    return app

Database/src/views.py
import base64
from flask import Blueprint, request, render_template, jsonify
from src import db
from src.models import Track
from datetime import date

main = Blueprint('main', __name__)

@main.get("/tracks")
def list_tracks():
    """Lists all tracks from the Track table of the database. 

    Returns
    -------
    JSON or HTML 
        JSON response if requested, otherwise renders an HTML template.
    """
    try:
        tracks = Track.query.all()
        
        if request.headers.get("Accept") == "application/json" or request.args.get("format") == "json":
            tracks_data = [
                {
                    "id": track.id,
                    "name": track.name,
                    "artist": track.artist,
                    "data": base64.b64encode(track.data).decode('utf-8') if track.data else None,
                    "cover": base64.b64encode(track.cover).decode('utf-8') if track.cover else None,
                    "release_date": track.release_date.isoformat() if track.release_date else None
                } for track in tracks                           
            ]
            
            return jsonify(tracks_data), 200
        
        return render_template('tracks.html', tracks=tracks, method=request.method)
    except Exception as e:
        return {"error": str(e)}, 500
    
@main.get("/tracks/<int:id>")
def get_track(id):
    """Gets a specific track from the Track table of the database.

    Parameters
    ----------
    id : int 
        The id of the track to be retrieved from the database. 

    Returns
    -------
    JSON or HTML 
        JSON response if requested, otherwise renders an HTML template.
    """

    try:    
        track = db.session.execute(db.select(Track).filter_by(id=id)).scalar_one()
        
        if request.headers.get("Accept") == "application/json" or request.args.get("format") == "json":
            return jsonify ({
                "id": track.id,
                "name": track.name,
                "artist": track.artist,
                "data": base64.b64encode(track.data).decode('utf-8') if track.data else None,
                "cover": base64.b64encode(track.cover).decode('utf-8') if track.cover else None,
                "release_date": track.release_date.isoformat() if track.release_date else None
            }), 200
        
        return render_template('tracks.html', track=track, method=request.method)
    except Exception as e:
        return str(e)

@main.post("/tracks")
def upload_track():
    """Uploads a track to the Track table of the database with the data provided in the upload form. 

    Returns
    -------
    str 
        an HTML display text.
    """

    try:
        artist = request.form["artist"]
        name = request.form["name"]
        release_date = date.fromisoformat(request.form["release_date"])

        data_file = request.files["data"]
        data = data_file.read()

        cover_file = request.files["cover"]
        cover = cover_file.read()

        track = Track(
            name=name,
            artist=artist,
            data=data,
            cover = cover,
            release_date = release_date
        )
        db.session.add(track)
        db.session.commit()
        return render_template("tracks.html", track=track, method=request.method)
    except Exception as e:
        db.session.rollback()
        return {"error": str(e)}, 500


@main.delete("/tracks/<int:id>")
def delete_track(id):
    """Deletes a specific track from the Track table of the database. 

    Parameters
    ----------
    id : int 
        The id of the track to be deleted in the database. 

    Returns
    -------
    str 
        an HTML display text. 
    """

    try:
        track = db.session.get(Track, id)
        db.session.delete(track)
        db.session.commit()
        return render_template("tracks.html", track=track, method=request.method)
    except Exception as e:
        db.session.rollback()
        return {"error": str(e)}, 500

@main.delete("/tracks")
def clear_tracks():
    """Clears the Track database from all its entries.

    Returns
    -------
    str 
        an HTML display text.
    """

    try:
        db.drop_all()
        return render_template("tracks.html", method=request.method)
    except Exception as e:
        return {"error": str(e)}, 500
    
@main.route("/")
def index():
    return "<p>Hello, world!</p>"
    

Database/src/templates/tracks.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Database</title>
    <link rel="stylesheet" href="{{ url_for('static',filename='styles/tracks.css') }}" />
</head>

<body>
    <div id="search">
        <h1 id="title">
            <a id="titleLink" href="/tracks">Catalogue</a>
        </h1>
        <input id="searchBar" type="text" onkeyup="", placeholder="Search artist names, track names, keywords, etc..">
    </div>

    <div id="tracks">
    {% if method == 'GET'%}
        {% if track is defined %}
                <div id="trackCover">
                    <img src="data:image/jpeg;base64, {{ track.cover | to_base64 }}"> <br>
                </div>
                <div id="trackInfo">
                    <h2> {{track.name}} by {{track.artist}}</h2>
                    <p> Released on {{track.release_date}} </p>
                </div>
        {% elif tracks is defined %}
            <h2 class="trackTitle">All Tracks:</h2>
                <ul id="trackList">
                    {% for track in tracks %}
                    <li class="trackItem"> <img src="data:image/jpeg;base64, {{ track.cover | to_base64 }}"> <a href="{{ url_for('main.get_track', id=track.id) }}"> {{track.name}} - {{track.artist}} </a></li>
                    {% endfor %}    
                </ul>
        {% else %}
            <p> Error </p>
        {% endif %}

    {% elif method == 'POST' %}
        <h2 class="trackTitle">Uploaded!</h2>        
            <p>Added: {{track.name}} by {{track.artist}}</p>

    {% elif method == 'DELETE' %}
        {% if track is defined %}
            <h2 class="trackTitle">Deleted!</h2>
                <p> Deleted: {{track.id}} - {{track.name}} - {{track.artist}} </p>
        {% else %}
            <h2 class="trackTitle">Cleared</h2>
                <p> The Track table of the database was successfully cleared. </p>
        {% endif %}
    {% endif %}
    </div>

    <div id="upload">
        <h2 id="uploadTitle">Upload!</h2>
        <form id="uploadForm" action="/tracks" method="post" enctype="multipart/form-data">

            <input class="uploadInput" id="uploadArtist" type="text" name="artist" placeholder="Artist Name"><br><br>
            <input class="uploadInput" id="uploadName" type="text" name="name" placeholder="Track Name"><br><br>

            <div id="uploadDate">
                <label for="date">Release Date:</label>
                <input type="date" name="release_date">
            </div>

            <label for="uploadData" id="customUploadData">
                Upload MP3      
            </label>
            <input id="uploadData" type="file" name="data" value="data">

            <label for="uploadCover" id="customUploadCover">
                Upload Cover
            </label>
            <input id="uploadCover" type="file" name="cover" value="cover">

            <input id="uploadSubmit" type="submit" value="SUBMIT">

        </form> 
    </div>
    
    <script>
        
    </script>
</body>
</html>